# Generated by Django 3.2.5 on 2021-07-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdfs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('autor', models.CharField(max_length=250)),
                ('fajlovi', models.FileField(upload_to='fajlovi/pdfs')),
            ],
        ),
    ]
