# Generated by Django 3.2.5 on 2021-08-23 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='fajl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orderapp.pdfs'),
        ),
    ]
