# Generated by Django 3.2.5 on 2021-07-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfs',
            name='fajlovi',
            field=models.FileField(upload_to='docs/pdfs'),
        ),
    ]
