# Generated by Django 3.2.5 on 2021-07-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0002_alter_pdfs_fajlovi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfs',
            name='fajlovi',
            field=models.FileField(upload_to='docs/pdfs/'),
        ),
    ]
