# Generated by Django 3.2.5 on 2021-08-24 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0004_alter_comment_fajl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='fajl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orderapp.pdfs'),
        ),
    ]
