# Generated by Django 3.2.5 on 2021-08-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfs',
            name='broj_stranica',
            field=models.IntegerField(null=True),
        ),
    ]
