# Generated by Django 3.2.5 on 2021-08-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0005_pdfs_broj_stranica'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfs',
            name='cena_stranica',
            field=models.IntegerField(null=True),
        ),
    ]
